params:
  paramsMapping:
    base-interface: http://10.74.1.92:8090
    cd-interface: http://10.74.1.92:8090
    resources-interface: http://10.74.1.92:8090
    wisdom-interface: http://10.74.1.92:8090
  #附件存放临时目录
  uploadPath: /usr/local/temp_image
  imageFormat:
    BMP,JPG,PNG,TIF,GIF,PCX,TGA,EXIF,FPX,SVG,PSD,CDR,PCD,DXF,UFO,EPS,AI,RAW,WMF,WEBP
  #附件服务器
  imagePath: http://10.74.0.66:9087